# Generated by Django 3.0.2 on 2020-05-08 07:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empid', models.IntegerField(unique=True)),
                ('empname', models.CharField(max_length=100, unique=True)),
                ('empmail', models.CharField(blank=True, max_length=100)),
                ('depid', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('depname', models.CharField(max_length=50)),
                ('depid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='first_app.Employee')),
            ],
        ),
    ]
