# Generated by Django 3.0.2 on 2020-05-08 07:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='depid',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='employee',
            name='depid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='first_app.Department'),
        ),
    ]
