# Generated by Django 3.0.2 on 2020-05-10 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0002_auto_20200508_1247'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sid', models.IntegerField(max_length=6, unique=True)),
                ('sname', models.CharField(max_length=100)),
            ],
        ),
    ]
